package enums;

public enum SkillCategory {
    TECHNICAL_PROGRAMMING,
    DATA_ANALYTICS,
    BUSINESS_MANAGEMENT,
    SOFT_SKILLS_INTERPERSONAL,
    CREATIVE_DESIGN,
    COOKING_CULINARY,
    LANGUAGES,
    CRAFTS_MAKING,
    MUSIC_PERFORMING_ARTS,
    SPORTS_FITNESS,
    HOME_LIFESTYLE
}